spring.profiles.active=${MODE:dev}

spring.application.name=telegram-leetcode-rpg

spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.data.redis.password=${REDIS_PASSWORD}

spring.threads.virtual.enabled=true

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}

application.max.user.command.count=10

boss.adjectives.file=classpath:static/boss-adjectives.txt
boss.hp.min=100
boss.hp.max=500
boss.fallback.name=Разрушитель api Eiztrips'а
boss.random.name.api=https://eiztrips.dev/api/fwd/funny-word

inactive.days.alarm=7
inactive.days.delete=30